### ISSUE TITLE
question about the train and validate data

### ISSUE THREAD

**Issue by loki369loki** [Jieqianyu/SSC-RS#5]
Sorry to bother you again.
I'm so confused about the use of datasets right now.

![image](https://github.com/Jieqianyu/SSC-RS/assets/100119921/438d36d4-afe4-40f6-af3c-b0fc1d1d3a44)

In this https://github.com/Jieqianyu/SSC-RS/issues/2#issuecomment-1645249137 
you say I should use the data represented by 2.
I download and extract it. Then I use the https://github.com/Jieqianyu/SSC-RS/blob/main/datasets/label_downsample.py to process it and get this.
![0554da278b2bbdebe3c4e6b457f9439](https://github.com/Jieqianyu/SSC-RS/assets/100119921/0848e05c-4910-4b4f-81f3-582065f145ed)

But in this https://github.com/Jieqianyu/SSC-RS/issues/4#issuecomment-1647287381https://github.com/Jieqianyu/SSC-RS/issues/4#issuecomment-1647287381, you say 
![image](https://github.com/Jieqianyu/SSC-RS/assets/100119921/3a3d2741-2dda-43ed-9696-a0ae62fa3f37)

And I revisited the code https://github.com/Jieqianyu/SSC-RS/blob/main/datasets/label_downsample.py. And I didn't find any code to control the interval between frames that generate data.

So I download the data represented by 1. The file structure of this data looks like this.
![image](https://github.com/Jieqianyu/SSC-RS/assets/100119921/409103a1-1b74-4331-a3e5-6a4e67cbd0d2)

If I process this data by https://github.com/Jieqianyu/SSC-RS/blob/main/datasets/label_downsample.py, I will get the same organization as you say https://github.com/Jieqianyu/SSC-RS/issues/4#issuecomment-1647287381https .

So, which data should I use? Is it the data represented by 1 or the data represented by 2?

**Comment by shenxiaowrj** [comment]
After change the version of the spconv and change data like this https://github.com/Jieqianyu/SSC-RS/issues/4#issuecomment-1647287381, I get the right results.
Now my question is that the data used during training is also like this?

![图片](https://github.com/Jieqianyu/SSC-RS/assets/100119921/75c82ebe-f116-41d4-9faa-9fe925725ef0)

Or like this.
![图片](https://github.com/Jieqianyu/SSC-RS/assets/100119921/f92843d3-0b03-4651-8a69-8969a119565e)

**Comment by Jieqianyu** [comment]
I double-check the website and the data (about 700 Mb) presented in 1 is needed. I'm so sorry to mislead you in #2 due to my careless.

**Comment by loki369loki** [comment]
> I double-check the website and the data (about 700 Mb) presented in 1 is needed. I'm so sorry to mislead you in #2 due to my careless.

OK. Thank you very much!
